DevTracker/Controllers/DashboardController.cs
using System.Linq;
using System.Web.Mvc;
using DevTracker.WebHelpers;
using Repository.Helpers;
using Repository.Models;
using Repository.Models.ViewModels;

namespace DevTracker.Controllers
{
    [CheckAuthorization]
    public class DashboardController : Controller
    {
        private DBEntities _entities = new DBEntities();

        public ActionResult Index()
        {
            using (_entities = new DBEntities())
            {
                var dashboardVm = new DashboardVm();

                //Total Resources
                var totalUsers = _entities.UserMasters.Where(s => s.RoleMasterId != (int) EnumList.Roles.Owner)
                    .ToList();
                dashboardVm.Tdesigner = totalUsers.Where(s => s.RoleMasterId == (int) EnumList.Roles.Developer).ToList()
                    .Count;
                dashboardVm.TprojectManager = totalUsers
                    .Where(s => s.RoleMasterId == (int) EnumList.Roles.Project_Manager).ToList().Count;
                dashboardVm.TteamLeader = totalUsers.Where(s => s.RoleMasterId == (int) EnumList.Roles.Team_Leader)
                    .ToList().Count;
                dashboardVm.TotalResource = totalUsers.Count;

                return View(dashboardVm);
            }
        }
    }
}

DevTracker/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DevTracker.WebHelpers;
using Repository.Helpers;
using Repository.Models;
using Repository.Models.ViewModels;

namespace DevTracker.Controllers
{
    [CheckAuthorization]
    public class ProjectsController : Controller
    {
        private DBEntities _entities = new DBEntities();

        public async Task<ActionResult> Create(long id = 0)
        {
            var projectsVm = new ProjectsVm();
            var roleMasterId = Convert.ToInt64(CookieHelper.GetCookie(CookieName.RoleMasterId));

            //Check that if we found id 0 and role not owener or PM
            if (id > 0 || roleMasterId == (int) EnumList.Roles.Owner ||
                roleMasterId == (int) EnumList.Roles.Project_Manager)
            {
                var project = await _entities.Projects.Where(s => s.ProjectId == id && !s.IsDelete)
                    .FirstOrDefaultAsync();

                if (project != null)
                {
                    projectsVm.CopyProperties(project);
                    projectsVm.StartDateString = project.StartDate.ToString("dd/MM/yyyy");
                    if (project.EndDate != null)
                        projectsVm.EndDateString = project.EndDate.Value.ToString("dd/MM/yyyy");

                    //Assign assigny list
                    if (project.ProjectAssignies.Any())
                    {
                        projectsVm.AssignyList = new string[project.ProjectAssignies.Count];
                        var i = 0;

                        foreach (var item in project.ProjectAssignies)
                        {
                            projectsVm.AssignyList[i] = item.AssignyId.ToString();
                            i++;
                        }
                    }
                }
            }

            return View(projectsVm);
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(ProjectsVm data)
        {
            using (_entities = new DBEntities())
            {
                var userMasterId = Convert.ToInt64(CookieHelper.GetCookie(CookieName.UserMasterId));

                if (data.ProjectId > 0)
                {
                    //Update Code HERE
                    var project = new Project();
                    project = await _entities.Projects.FindAsync(data.ProjectId);

                    if (project != null)
                    {
                        project.BasicDescription = data.BasicDescription;
                        project.Budget = data.Budget;
                        project.ClientName = data.ClientName;
                        project.ConfidentialDescription = data.ConfidentialDescription;
                        project.EstimateHours = data.EstimateHours;
                        project.LiveURL = data.LiveURL;
                        project.Name = data.Name;
                        project.ClientName = data.ClientName;
                        project.TagLine = data.TagLine;
                        project.TeamMemberCount = data.TeamMemberCount;
                        project.UpdatedBy = userMasterId;
                        project.UpdatedDate = DateTime.Now;
                        project.StartDate = DateTime.ParseExact(data.StartDateString,
                            data.StartDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                            CultureInfo.InvariantCulture);

                        if (!string.IsNullOrWhiteSpace(data.EndDateString))
                            project.EndDate = DateTime.ParseExact(data.EndDateString,
                                data.EndDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                                CultureInfo.InvariantCulture);
                        _entities.Entry(project).State = EntityState.Modified;
                        await _entities.SaveChangesAsync();


                        //Delete Existing Assigny and Add new Assigny and Save assigny list HERE
                        if (data.AssignyList.Any())
                        {
                            var projectAssignys = await _entities.ProjectAssignies
                                .Where(s => s.ProjectId == data.ProjectId).ToListAsync();

                            if (projectAssignys.Any())
                            {
                                _entities.ProjectAssignies.RemoveRange(projectAssignys);
                                await _entities.SaveChangesAsync();
                            }

                            projectAssignys = new List<ProjectAssigny>();

                            projectAssignys = data.AssignyList.Select(item => new ProjectAssigny
                            {
                                ProjectId = project.ProjectId,
                                AssignyId = Convert.ToInt64(item),
                                CreatedBy = userMasterId,
                                CreatedDate = DateTime.Now,
                                WhoAssign = userMasterId
                            }).ToList();

                            _entities.ProjectAssignies.AddRange(projectAssignys);
                            await _entities.SaveChangesAsync();
                        }

                        //Delete existing attachment and Save new attachment
                        if (data.AttachedFiles != null && data.AttachedFiles.Any())
                        {
                            var projectAttachments = await _entities.ProjectAttachments
                                .Where(s => s.ProjectId == data.ProjectId).ToListAsync();

                            if (projectAttachments.Any())
                            {
                                _entities.ProjectAttachments.RemoveRange(projectAttachments);
                                await _entities.SaveChangesAsync();
                            }

                            projectAttachments = (from item in data.AttachedFiles
                                where item != null
                                select new ProjectAttachment
                                {
                                    ProjectId = project.ProjectId,
                                    CreatedBy = userMasterId,
                                    CreatedDate = DateTime.Now,
                                    DisplayName = item.FileName,
                                    FileName = Utilities.SaveFile(item,
                                        Server.MapPath("~" + BasicProperty.ProjectAttachmentPath + project.ProjectId +
                                                       "/"), Guid.NewGuid().ToString()),
                                    FileSize = item.ContentLength / 1024
                                }).ToList();

                            if (projectAttachments.Any())
                                _entities.ProjectAttachments.AddRange(projectAttachments);
                        }

                        TempData["Success"] = "Project updated successfully";
                    }
                    else
                    {
                        TempData["Error"] = "Request failed! Please try after some time.";
                    }
                }
                else
                {
                    //Save data in project table
                    var project = new Project();
                    project.CopyProperties(data);
                    project.ProjectStatusMasterId = data.ProjectStatusMasterId;
                    project.IsActive = true;
                    project.IsDelete = false;
                    project.CreatedBy = userMasterId;
                    project.CreatedDate = DateTime.Now;
                    project.StartDate = DateTime.ParseExact(data.StartDateString,
                        data.StartDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy", CultureInfo.InvariantCulture);

                    if (!string.IsNullOrWhiteSpace(data.EndDateString))
                        project.EndDate = DateTime.ParseExact(data.EndDateString,
                            data.EndDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                            CultureInfo.InvariantCulture);
                    _entities.Projects.Add(project);
                    await _entities.SaveChangesAsync();

                    // Save assigny list HERE
                    if (data.AssignyList.Any())
                    {
                        var projectAssignys = data.AssignyList.Select(item => new ProjectAssigny
                        {
                            ProjectId = project.ProjectId,
                            AssignyId = Convert.ToInt64(item),
                            CreatedBy = userMasterId,
                            CreatedDate = DateTime.Now,
                            WhoAssign = userMasterId
                        }).ToList();

                        _entities.ProjectAssignies.AddRange(projectAssignys);
                        await _entities.SaveChangesAsync();
                    }


                    //Save attachment

                    if (data.AttachedFiles != null && data.AttachedFiles.Any())
                    {
                        var projectAttachments = (from item in data.AttachedFiles
                            where item != null
                            select new ProjectAttachment
                            {
                                ProjectId = project.ProjectId,
                                CreatedBy = userMasterId,
                                CreatedDate = DateTime.Now,
                                DisplayName = item.FileName,
                                FileName = Utilities.SaveFile(item,
                                    Server.MapPath("~" + BasicProperty.ProjectAttachmentPath + project.ProjectId + "/"),

DevTracker/Views/Projects/Details.cshtml
@model Tuple<ProjectsListVm, List<UserMaster>>

@{
    ViewBag.Title = "Details";
    var count = 1;
    var projectfileUrl = BasicProperty.ProjectAttachmentPath + Model.Item1.ProjectId + "/";
    var profilePath = BasicProperty.ProfilePath;
    const string defaultImage = "/Content/img/userIcon.jpg";
}

<!-- Page header -->
<div class="header">
    <div class="header-content">
        <div class="page-title">
            <i class="icon-briefcase3 position-left"></i> Projects Details
        </div>
        <ul class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Dashboard")"></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li>
                <a href="@Url.Action("List", "Projects")">Project</a>
            </li>
            <li class="active">Projects Details</li>
        </ul>
    </div>
</div>

<div class="container-fluid page-content">

<div class="row">
<div class="col-md-8">

    <!-- Project details -->
    <div class="panel panel-default no-margin-bottom no-border-bottom">
        <div class="panel-heading">
            <div class="panel-title text-xlg">@Model.Item1.Name</div>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <h5 class="text-indigo">
                        @Model.Item1.TagLine
                    </h5>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-right">
                    <a class="text-info" href="@Model.Item1.LiveURL"> @Model.Item1.LiveURL </a>
                </div>
            </div>

            <div class="row m-t-20">
                <div class="col-md-12">
                    <h4 class="m-b-10 text-semibold">Basic description</h4>
                    @Html.Raw(Model.Item1.BasicDescription)
                </div>
            </div>
        </div>
    </div>
    <!-- /Project details -->
    <!-- Files -->
    <div class="panel panel-flat no-margin-top no-margin-bottom no-border-bottom">
        <div class="panel-heading">
            <div class="panel-title">Files</div>
        </div>
        <div class="panel-body">
            @foreach (var item in Model.Item1.ProjectAttachments)
            {
                if (count == 1)
                {
                    <div class="row">
                        <div class="col-md-1 col-xs-2">
                            <i class="icon-files-empty2 icon-2x m-t-5"></i>
                        </div>
                        <div class="col-md-7 col-xs-5">
                            <div class="no-padding no-margin">
                                @item.DisplayName
                                <small class="display-block">
                                    @item.FileSize KB
                                </small>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-5 text-right">
                            <a target="_blank" href="@projectfileUrl@item.FileName" class="btn btn-default btn-xs"><i class="icon-download4 position-left"></i>Download</a>
                        </div>
                    </div>
                }
                else
                {
                    <div class="row m-t-20">
                        <div class="col-md-1 col-xs-2">
                            <i class="icon-files-empty2 icon-2x m-t-5"></i>
                        </div>
                        <div class="col-md-7 col-xs-5">
                            <div class="no-padding no-margin">
                                @item.DisplayName
                                <small class="display-block">
                                    @item.FileSize MB
                                </small>
                            </div>
                        </div>
                        <div class="col-md-4 col-xs-5 text-right">
                            <a target="_blank" href="@projectfileUrl@item.FileName" class="btn btn-default btn-xs"><i class="icon-download4 position-left"></i>Download</a>
                        </div>
                    </div>
                }

                count++;
            }

        </div>
    </div>
    <!-- /Files -->
    <!-- Comments -->
    <div class="panel panel-flat no-margin-top">
        <div class="panel-heading">
            <div class="panel-title">Comments</div>
        </div>
        <div class="panel-body">
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img src="http://via.placeholder.com/80x80" class="img-circle" alt="">
                    </a>
                </div>

                <div class="media-body">
                    <h6 class="media-heading">Marilyn Romero<span class="media-annotation pull-right">2 hours ago</span></h6>
                    Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.

                    <ul class="list-inline m-t-5">
                        <li>
                            <a href="#"><i class="icon-reply text-success position-left"></i>Reply</a>
                        </li>
                        <li>
                            <a href="#"><i class="icon-pencil6 text-danger position-left"></i>Edit</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img src="http://via.placeholder.com/80x80" class="img-circle" alt="">
                    </a>
                </div>

                <div class="media-body">
                    <h6 class="media-heading">Jonaly Smith<span class="media-annotation pull-right">1 day ago</span></h6>
                    Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

                    <ul class="list-inline m-t-5">
                        <li>
                            <a href="#"><i class="icon-reply text-success position-left"></i>Reply</a>
                        </li>
                        <li>
                            <a href="#"><i class="icon-pencil6 text-danger position-left"></i>Edit</a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img src="http://via.placeholder.com/80x80" class="img-circle" alt="">
                    </a>
                </div>

                <div class="media-body">
                    <h6 class="media-heading">John Deo<span class="media-annotation pull-right">3 days ago</span></h6>
                    Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.

                    <ul class="list-inline m-t-5">
                        <li>
                            <a href="#"><i class="icon-reply text-success position-left"></i>Reply</a>
                        </li>
                        <li>
                            <a href="#"><i class="icon-pencil6 text-danger position-left"></i>Edit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- /Comments -->

</div>

<div class="col-md-4">
    <div class="panel panel-flat">
        <div class="panel-body">
            <div class="row">
                <div class="col-md-6">
                    <p class="no-margin">Total Team Memebr:</p>
                </div>

                <div class="col-md-6 text-right">
                    <p class="text-semibold no-margin"> @Model.Item1.TeamMemberCount </p>
                </div>
            </div>
            <div class="row m-t-5">
                <div class="col-md-6">
                    <p class="no-margin">Actual Team Member:</p>
                </div>

                <div class="col-md-6 text-right">
                    <p class="text-semibold no-margin">@Model.Item1.ActualTeamMemberCount</p>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-t-0 m-b-10">Current status</h4>
                    <div class="progress m-t-5">
                        <div class="progress-bar progress-bar-success progress-bar-striped active" style="width: 55%">
                            <span class="sr-only">55% Complete (success)</span>
                        </div>
                    </div>
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-t-0 m-b-10">Assigned to</h4>

                    @foreach (var userData in Model.Item1.ProjectAssignyAssignies.Select(item2 => Model.Item2.FirstOrDefault(s => s.UserMasterId == item2.AssignyId)))
                    {
                        if (userData != null)
                        {
                            if (!string.IsNullOrWhiteSpace(userData.Profile))
                            {
                                <img alt="@userData.Name" src="@profilePath@(userData.Profile)" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                            }
                            else
                            {
                                <img alt="" src="@defaultImage" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                            }
                        }
                        else
                        {
                            <img alt="" src="@defaultImage" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                        }
                    }
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-t-0 m-b-15">Project details</h4>
                    <div class="row">
                        <div class="col-md-6 col-xs-6">
                            <h5>Client name</h5>
                            <h5>Assignee</h5>
                            <h5>Start Date</h5>
                            <h5>Deadline</h5>
                            <h5>Budget</h5>
                        </div>

                        <div class="col-md-6 col-xs-6 text-right">
                            <h5 class="text-semibold">@Model.Item1.ClientName</h5>
                            <h5 class="text-semibold">Client name</h5>
                            <h5 class="text-semibold">@Model.Item1.StartDate.ToString("MMMM dd, yyyy")</h5>
                            <h5 class="text-semibold">
                                @if (Model.Item1.EndDate != null)
                                {
                                    @Model.Item1.EndDate.Value.ToString("MMMM dd, yyyy")
                                }
                                else
                                {
                                    <span>N/A</span>
                                }
                            </h5>
                            <h5>
                                @if (Model.Item1.Budget != null)
                                {
                                    <span>@Model.Item1.Budget.Value.ToString("0.00") INR</span>
                                }
                                else
                                {
                                    <span>N/A</span>
                                }

                            </h5>
                        </div>
                    </div>
                </div>
            </div>

            <hr>
            <div class="row">
                <div class="col-md-12">
                    <h4 class="m-t-0 m-b-15">Options</h4>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" class="styled" checked="checked">
                            Send project report by email
                        </label>
                    </div>
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" class="styled">
                            Send all notifications by email
                        </label>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

</div>

DevTracker/Views/Projects/List.cshtml
@model Tuple<List<ProjectsListVm>, List<UserMaster>>

@{
    ViewBag.Title = "List";
    var count = 1;
    var profilePath = BasicProperty.ProfilePath;
    const string defaultImage = "/Content/img/userIcon.jpg";
}

<!-- Page header -->
<div class="header">
    <div class="header-content">
        <div class="page-title">
            <i class="icon-briefcase3 position-left"></i> Projects
        </div>
        <ul class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Dashboard")"></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li class="active">Projects</li>
        </ul>
    </div>
</div>

<div class="container-fluid page-content">

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

            <div class="panel panel-flat">
                <div class="panel-heading">
                    <div class="panel-title">All Projects</div>
                </div>

                <table class="table table-hover invoice-list" id="datatable">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Client</th>
                        <th>Deadline</th>
                        <th>Started on</th>
                        <th>Status</th>
                        <th>Completed</th>
                        <th>Team</th>
                        <th class="text-center">Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (Model.Item1.Any())
                    {
                        foreach (var item in Model.Item1)
                        {
                            <tr>
                                <td>@count</td>
                                <td>@item.Name</td>
                                <td>
                                    <div class="no-margin">
                                        <a href="#">@item.ClientName</a>
                                    </div>
                                </td>
                                <td>
                                    @if (item.EndDate != null)
                                    {
                                        @item.EndDate.Value.ToString("MMMM dd, yyyyy")
                                    }
                                    else
                                    {
                                        <span> N/A </span>
                                    }

                                </td>
                                <td>
                                    @item.StartDate.ToString("MMMM dd, yyyyy")
                                </td>
                                <td>
                                    @switch (item.ProjectStatusMasterId)
                                    {
                                        case (int) EnumList.ProjectStatus.Contract_signed_not_begun:
                                            <span class="label label-success">Contract signed not begun</span>
                                            break;
                                        case (int) EnumList.ProjectStatus.On_Live:
                                            <span class="label label-success">On Live</span>
                                            break;
                                        case (int) EnumList.ProjectStatus.On_Development:
                                            <span class="label label-info">On Development</span>
                                            break;
                                        case (int) EnumList.ProjectStatus.On_Hold:
                                            <span class="label label-warning">On Hold</span>
                                            break;
                                        case (int) EnumList.ProjectStatus.On_Staging:
                                            <span class="label label-primary">On Staging</span>
                                            break;
                                        default:
                                            <span class="label label-default">N/A</span>
                                            break;
                                    }
                                </td>
                                <td>
                                    <div class="progress progress-xs">
                                        <div class="progress-bar progress-bar-success progress-bar-striped active" style="width: 75%">
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    @foreach (var userData in item.ProjectAssignyAssignies.Select(item2 => Model.Item2.FirstOrDefault(s => s.UserMasterId == item2.AssignyId)))
                                    {
                                        if (userData != null)
                                        {
                                            if (!string.IsNullOrWhiteSpace(userData.Profile))
                                            {
                                                @:<img alt="@userData.Name" src="@profilePath@(userData.Profile)" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                                            }
                                            else
                                            {
                                                @:<img alt="" src="@defaultImage" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                                            }
                                        }
                                        else
                                        {
                                            @:<img alt="" src="@defaultImage" class="img-circle img-responsive img-xs pull-left m-l-3 m-r-3">
                                        }
                                    }
                                </td>
                                <td class="text-center">
                                    <ul class="icons-list">
                                        <li>
                                            <a href="@Url.Action("Details", "Projects", new {id = item.ProjectId})">
                                                <i class="icon-eye2"></i>
                                            </a>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                            count++;
                        }
                    }
                    else
                    {
                        <tr>
                            <th colspan="9">
                                <label>No project found.</label>
                            </th>
                        </tr>
                    }

                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>

DevTracker/Views/Projects/TimeLine.cshtml
@{
    ViewBag.Title = "TimeLine";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TimeLine</h2>