DevTracker/Controllers/DashboardController.cs
using System.Linq;
using System.Web.Mvc;
using DevTracker.WebHelpers;
using Repository.Helpers;
using Repository.Models;
using Repository.Models.ViewModels;

namespace DevTracker.Controllers
{
    [CheckAuthorization]
    public class DashboardController : Controller
    {
        private DBEntities _entities = new DBEntities();

        public ActionResult Index()
        {
            using (_entities = new DBEntities())
            {
                var dashboardVm = new DashboardVm();

                //Total Resources
                var totalUsers = _entities.UserMasters.Where(s => s.RoleMasterId != (int) EnumList.Roles.Owner)
                    .ToList();
                dashboardVm.Tdesigner = totalUsers.Where(s => s.RoleMasterId == (int) EnumList.Roles.Developer).ToList()
                    .Count;
                dashboardVm.TprojectManager = totalUsers
                    .Where(s => s.RoleMasterId == (int) EnumList.Roles.Project_Manager).ToList().Count;
                dashboardVm.TteamLeader = totalUsers.Where(s => s.RoleMasterId == (int) EnumList.Roles.Team_Leader)
                    .ToList().Count;
                dashboardVm.TotalResource = totalUsers.Count;

                return View(dashboardVm);
            }
        }
    }
}

DevTracker/Controllers/TasksController.cs
using System;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using DevTracker.WebHelpers;
using Repository.Helpers;
using Repository.Models;
using Repository.Models.ViewModels;

namespace DevTracker.Controllers
{
    [CheckAuthorization]
    public class TasksController : Controller
    {
        private DBEntities _entities = new DBEntities();

        public async Task<ActionResult> Create(long id = 0)
        {
            using (_entities = new DBEntities())
            {
                if (TempData["Success"] != null)
                    TempData["Success"] = TempData["Success"];

                var taskVm = new TaskVm();
                var roleMasterId = Convert.ToInt64(CookieHelper.GetCookie(CookieName.RoleMasterId));

                //Check that if we found id 0 and role not owener or PM
                if (id > 0 || roleMasterId == (int)EnumList.Roles.Owner ||
                    roleMasterId == (int)EnumList.Roles.Project_Manager)
                {
                    var taskMaster =
                        await
                            _entities.TaskMasters.Where(s => s.TaskMasterId == id && !s.IsDelete)
                                .FirstOrDefaultAsync();

                    if (taskMaster != null)
                    {
                        taskVm.CopyProperties(taskMaster);
                        taskVm.StartDateString = taskMaster.StartDate.ToString("dd/MM/yyyy");
                        if (taskMaster.EndDate != null)
                            taskVm.EndDateString = taskMaster.EndDate.Value.ToString("dd/MM/yyyy");
                    }
                }
                else
                {
                    taskVm.Description =
                        "<p><strong>Objective:</strong></p><p>&nbsp;</p><p><strong>References:</strong></p><p>&nbsp;</p><p><strong>Condition Satisfied:</strong></p>";
                }

                return View(taskVm);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(TaskVm data)
        {
            using (_entities)
            {
                var projectDetails = await _entities.Projects.FindAsync(data.ProjectId);
                var taskCount = await _entities.TaskCategories.Where(s => s.ProjectId == data.ProjectId).ToListAsync();
                var currentTask = taskCount.Count + 1;
                var userMasterId = Convert.ToInt64(CookieHelper.GetCookie(CookieName.UserMasterId));

                if (data.TaskMasterId > 0)
                {
                    //Update code HERE
                    var taskmaster = await _entities.TaskMasters.FindAsync(data.TaskMasterId);

                    if (taskmaster != null)
                    {
                        taskmaster.ProjectId = data.ProjectId;
                        taskmaster.ActualTimeHours = data.ActualTimeHours;
                        taskmaster.AssignyId = data.AssignyId;
                        taskmaster.Description = data.Description;
                        taskmaster.EstimateTimeHours = data.EstimateTimeHours;
                        taskmaster.PriorityMasterId = data.PriorityMasterId;
                        taskmaster.TaskStatusMasterId = data.TaskStatusMasterId;
                        taskmaster.UpdatedBy = userMasterId;
                        taskmaster.UpdatedDate = DateTime.Now;
                        taskmaster.StartDate = DateTime.ParseExact(data.StartDateString,
                            data.StartDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                            CultureInfo.InvariantCulture);
                        if (!string.IsNullOrWhiteSpace(data.EndDateString))
                            taskmaster.EndDate = DateTime.ParseExact(data.EndDateString,
                                data.EndDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                                CultureInfo.InvariantCulture);
                        _entities.Entry(taskmaster).State = EntityState.Modified;
                        await _entities.SaveChangesAsync();

                        //Delete existing attachment and Save new attachment
                        if (data.AttachedFiles.Any())
                        {
                            var taskAttachments = await _entities.TaskAttachments
                                .Where(s => s.TaskMasterId == data.TaskMasterId).ToListAsync();

                            if (taskAttachments.Any())
                            {
                                _entities.TaskAttachments.RemoveRange(taskAttachments);
                                await _entities.SaveChangesAsync();
                            }

                            taskAttachments = (from item in data.AttachedFiles
                                               where item != null
                                               select new TaskAttachment
                                               {
                                                   TaskMasterId = taskmaster.TaskMasterId,
                                                   CreatedBy = userMasterId,
                                                   CreatedDate = DateTime.Now,
                                                   DisplayName = item.FileName,
                                                   FileName = Utilities.SaveFile(item,
                                                       Server.MapPath("~" + BasicProperty.ProjectAttachmentPath + taskmaster.ProjectId +
                                                                      "/"), Guid.NewGuid().ToString()),
                                                   FileSize = item.ContentLength / 1024
                                               }).ToList();

                            if (taskAttachments.Any())
                                _entities.TaskAttachments.AddRange(taskAttachments);

                            TempData["Success"] = "Task updated successfully";
                        }
                    }
                    else
                    {
                        TempData["Error"] = "Request failed! Please try after some time.";
                    }
                }
                else
                {
                    //Save task details in taskmaster table
                    var taskmaster = new TaskMaster();
                    taskmaster.CopyProperties(data);
                    taskmaster.TaskCode = projectDetails != null
                        ? "[" + projectDetails.Name.Substring(0, 2).ToUpper() + "-" + currentTask + "]"
                        : "[" + currentTask + "]";
                    taskmaster.CreatedBy = userMasterId;
                    taskmaster.CreatedDate = DateTime.Now;
                    taskmaster.StartDate = DateTime.ParseExact(data.StartDateString,
                        data.StartDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy", CultureInfo.InvariantCulture);
                    if (!string.IsNullOrWhiteSpace(data.EndDateString))
                        taskmaster.EndDate = DateTime.ParseExact(data.EndDateString,
                            data.EndDateString.Contains('-') ? "dd-MM-yyyy" : "dd/MM/yyyy",
                            CultureInfo.InvariantCulture);
                    _entities.TaskMasters.Add(taskmaster);
                    await _entities.SaveChangesAsync();

                    //Save attached file if any found
                    if (data.AttachedFiles.Any())
                    {
                        var taskAttachments = (from item in data.AttachedFiles
                                               where item != null
                                               select new TaskAttachment
                                               {
                                                   TaskMasterId = taskmaster.TaskMasterId,
                                                   CreatedBy = userMasterId,
                                                   CreatedDate = DateTime.Now,
                                                   DisplayName = item.FileName,
                                                   FileName = Utilities.SaveFile(item,
                                                       Server.MapPath("~" + BasicProperty.ProjectAttachmentPath + taskmaster.ProjectId +
                                                                      "/"), Guid.NewGuid().ToString()),
                                                   FileSize = item.ContentLength / 1024
                                               }).ToList();

                        if (taskAttachments.Any())
                            _entities.TaskAttachments.AddRange(taskAttachments);
                    }

                    //Save call
                    await _entities.SaveChangesAsync();

                    TempData["Success"] = "Task added successfully";
                }
            }

            return RedirectToAction("Create");
        }

        public async Task<ActionResult> Details(long id = 0)
        {
            using (_entities = new DBEntities())
            {
                var taskDetailsVm = new TaskDetailsVm();

                var taskMaster = await _entities.TaskMasters.Where(s => s.TaskMasterId == id && !s.IsDelete)
                    .FirstOrDefaultAsync();

                if (taskMaster != null)
                {
                    //Assigny task details to view model
                    taskDetailsVm.CopyProperties(taskMaster);

                    //Convert data to string format
                    taskDetailsVm.StartDateString = taskMaster.StartDate.ToString("dd/MM/yyyy");
                    if (taskMaster.EndDate != null)
                        taskDetailsVm.EndDateString = taskMaster.EndDate.Value.ToString("dd/MM/yyyy");

                    //Get task attachments

DevTracker/Views/Tasks/Details.cshtml
@model TaskDetailsVm

@{
    ViewBag.Title = "Details";
    var projectfileUrl = BasicProperty.ProjectAttachmentPath + Model.ProjectId + "/";
    var profilePath = BasicProperty.ProfilePath;
    const string defaultImage = "/Content/img/userIcon.jpg";
}

<style>
    .taskDetlHead {
        font-size: 13px;
        font-weight: 500;
        padding-right: 5px;
    }

    .taskDetlBody { border-bottom: 1px dotted #1c2b36; }
</style>


<div class="header">
    <div class="header-content">
        <div class="page-title">
            <i class="icon-briefcase3 position-left"></i> Task Details
        </div>
        <ul class="breadcrumb">
            <li>
                <a href="@Url.Action("Index", "Dashboard")"></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "Dashboard")">Dashboard</a>
            </li>
            <li class="active">Task Details</li>
        </ul>
    </div>
</div>

@Html.HiddenFor(s => s.TaskMasterId)

<div class="container-fluid page-content">

    <div class="row">
        <div class="col-md-9">

            <!-- Project details -->
            <div class="panel panel-default no-margin-bottom no-border-bottom">
                <div class="panel-heading">
                    <div class="panel-title text-xlg">@Model.Title</div>
                </div>
                <div class="panel-body">
                    <div class="row m-t-5">
                        <div class="col-md-12">
                            <h4 class="m-b-10 text-indigo">
                                @Model.Title
                            </h4>
                        </div>
                        <div class="col-md-12">
                            <h4 class="m-b-10 text-semibold">Description</h4>
                            @Html.Raw(Model.Description)
                            <hr/>
                        </div>
                    </div>

                    <div class="panel-body" style="padding: 10px 0 !important;">
                        <div class="tabbable">
                            <ul class="nav nav-tabs nav-tabs-highlight">
                                <li class="active">
                                    <a href="#left-icon-tab1" data-toggle="tab">
                                        <i class="icon-files-empty2"></i> Documents
                                    </a>
                                </li>
                                <li>
                                    <a href="#left-icon-tab2" data-toggle="tab">
                                        <i class="icon-comment-discussion"></i> Comments
                                    </a>
                                </li>
                                <li>
                                    <a href="#left-icon-tab3" data-toggle="tab">
                                        <i class="icon-grid5"></i> Activities
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content">
                                @*Comments*@
                                <div class="tab-pane active" id="left-icon-tab1">
                                    Add icon markup <code>before</code> tab nav text to display icons on the left side.
                                </div>
                                @*Documents TAB*@
                                <div class="tab-pane" id="left-icon-tab2">
                                    Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.
                                </div>
                                @*Activities TAB*@
                                <div class="tab-pane" id="left-icon-tab3">
                                    load partial hERE

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /Project details -->
        </div>

        <div class="col-md-3">
            <div class="panel-group panel-group-control panel-group-control-right accordion" id="accordion-control-right">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion-control-right" href="#accordion-control-right-group1">Details</a>
                        </div>
                    </div>
                    <div id="accordion-control-right-group1" class="panel-collapse collapse in">
                        <div class="panel-body">

                            <label>
                                <span class="taskDetlHead text-muted">Project: </span>
                                <span class="taskDetlBody">Zemulla</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Task Type: </span>
                                <span class="taskDetlBody">Bug</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Task Category: </span>
                                <span class="taskDetlBody">Logo design</span>
                            </label>

                            <hr/>
                            <label>
                                <span class="taskDetlHead text-muted">Assignee: </span>
                                <span class="taskDetlBody">
                                    <a href="javascript:void(0);" data-placement="top" data-popup="popover" title="Select assignee"
                                       data-html="true" data-content="Add <u>some</u> <i>HTML</i> <strong>stuff</strong>.">
                                        Ankit Kanojia
                                    </a>
                                </span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Reporter: </span>
                                <span class="taskDetlBody">Suchit Khunt</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Task Priority: </span>
                                <span class="taskDetlBody">Dropdown</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Task Status: </span>
                                <span class="taskDetlBody">
                                    <a href="javascript:void(0);" onclick="taskStatusPopover()" data-html="true" id="test">
                                        Ankit Kanojia
                                    </a>
                                </span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Start date: </span>
                                <span class="taskDetlBody">16/04/1993</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Goal Date: </span>
                                <span class="taskDetlBody">10/12/2017</span>
                            </label>

                            <br/>
                            <label>
                                <span class="taskDetlHead text-muted">Estimate Hours: </span>
                                <span class="taskDetlBody">200</span>
                            </label>

                            <hr/>
                            <label>
                                <span class="taskDetlHead text-muted">Completion (%) </span>
                                <br/><br/>
                                <div id="noui-slider-connect-lower"></div>
                                <div class="val-demo m-b-5 text-success">Value: <span id="noui-slider-connect-lower-val"></span></div>
                            </label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script src="~/Content/lib/js/forms/nouislider.min.js"></script>

    <script>

        function taskStatusPopover() {
            $('#test').popover({
                placement: "top",
                trigger: "manual",
                content: "suchit"
            }).popover("show");
            //$('#target').popover({
            //    placement: "left",
            //    trigger: "manual",
            //    content: $("#popover-content").parent().html()
            //}).popover("show");
        }

        //Change task field value
        function changeTaskField(id) {
            /*
                id == 1 == Assignee
                id == 2 == Reporter
                id == 3 == Priority
                id == 4 == Task Status
                id == 5 == Completion Percentage
            */

            var taskMasterId = $('#TaskMasterId').val();
            var changeValue = 0;

            switch (id) {
            case 1:
                changeValue = 1;
                break;
            case 2:
                changeValue = 2;
                break;
            case 3:
                changeValue = 3;
                break;
            case 4:
                changeValue = 4;
                break;
            case 5:
                changeValue = 5;
                break;
            }

            $.ajax({
                type: "POST",
                url: '@Url.Action("ChangeTaskField", "Tasks")',
                datatype: "json",
                data: { taskMasterId: taskMasterId, changeType: id, changeValue: changeValue },
                success: function(data) {
                }
            });
        }


        $(document).ready(function() {

            //#Start: UI Slider
            var slider_connect_lower = document.getElementById('noui-slider-connect-lower');
            noUiSlider.create(slider_connect_lower,
                {
                    start: 0,
                    connect: 'lower',
                    range: {
                        'min': 0,
                        'max': 100
                    }
                });
            $('#noui-slider-connect-lower').css('width', '226px');
            var slider_connect_lower_val = document.getElementById('noui-slider-connect-lower-val');
            slider_connect_lower.noUiSlider.on('update',
                function(values, handle) {
                    var value = values[handle];
                    if (handle) {
                        inputNumber.value = value;
                    } else {
                        slider_connect_lower_val.innerHTML = Math.round(value);
                    }
                    //slider_connect_lower_val.innerHTML = values[handle];
                });
            //#End: UI Slider
        });
    </script>
}

DevTracker/Views/Tasks/_GetActivities.cshtml
@model IEnumerable<Activity>

<div class="panel panel-flat">
    <div class="panel-heading">
        <h5 class="panel-title">
            Recent Activities
        </h5>
    </div>
    <div class="panel-body p-l-20 p-b-20">
        <br/>
        <div class="streamline">
            <div class="sl-item sl-primary">
                <div class="sl-content">
                    <small class="text-muted">
                        <i class="icon-user-plus position-left"></i>2 mins ago
                    </small>
                    <p>Lorem Ipsum is simply dummy text.</p>
                </div>
            </div>

            <div class="sl-item sl-danger">
                <div class="sl-content">
                    <small class="text-muted"><i class="icon-pencil5 position-left"></i>10 mins ago</small>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry..</p>
                </div>
            </div>

            <div class="sl-item sl-success">
                <div class="sl-content">
                    <small class="text-muted"><i class="icon-user position-left"></i>14 mins ago</small>
                    <p>Lorem Ipsum is simply dummy text.</p>
                </div>
            </div>

            <div class="sl-item sl-warning">
                <div class="sl-content">
                    <small class="text-muted"><i class="icon-calendar position-left"></i>20 mins ago</small>
                    <p>Lorem Ipsum is simply dummy text.</p>
                </div>
            </div>

            <div class="sl-item sl-primary">
                <div class="sl-content">
                    <small class="text-muted"><i class="icon-user-plus position-left"></i>1 day ago</small>
                    <p>Lorem Ipsum is simply dummy text.</p>
                </div>
            </div>

            <div class="sl-item sl-success">
                <div class="sl-content">
                    <small class="text-muted"><i class="icon-comments position-left"></i>1 day ago</small>
                    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry..</p>
                </div>
            </div>
        </div>
    </div>
</div>

DevTracker/Views/Tasks/_GetComments.cshtml
@model IEnumerable<CommentMaster>